### ISSUE TITLE
Optimize `constraints` by removing all if one evaluates to false

### ISSUE THREAD

**Issue by lethalgem** [essential-contributions/pint#853]
If any `constraints` evaluate to `false` just remove every constraint there is and add a `constraint false`. You know the program is going to fail every single time and every other `constraint` is useless. Effectively this is just merging all the `constraints` into the simplest form.

1. evaluate the constraints
2. the moment you find a false
3. exit and clear out the constraints vector
4. add a new constraint equal to false (look at how to add a expr of false, there are examples)
5. give it an empty span

**Comment by otrho** [comment]
And emit a huge warning to the user saying 'this predicate cannot be satisfied' or something..?  With the constraint in question ideally.  Removing all the other constraints is probably overkill.

**Comment by otrho** [comment]
OK, sure, since this is an optimisation then if it's on it should minimise the contract.  Fair enough.  So as per the other optimisation discussion if we have a (hidden or not) flag to disable optimisations then everything should remain.

It just felt a bit weird to 'punish' the good constraints for being associated with a bad one, but I guess it really is just DCE.  It's like having a `return` at the start of `main()` -- there's no point in emitting any other functions in the program. :slightly_smiling_face:
